# Site settings
description: A blog about lorem ipsum dolor sit amet
url: "http://koesystems.github.io"

# User settings
username: Koe
user_description: Systems Engineer
user_title: Systems Engineer
email: koe.systems@gmail.com
linkedin_username: joseluispenadesanvictor
twitter_username: KoeSystems
github_username:  KoeSystems
disqus_username: koesystemsgithubio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
